#!/bin/bash
#SBATCH -J agalma
#SBATCH -t 4:00:00
#SBATCH -c 8

##Note that you should check that the homology run corresponds to the homologize run after treeinform.

export AGALMA_DB="/home/cm2477/scratch60/siphonophore2016/agalma-siphonophora.sqlite"

mkdir OrthoFinder
cd OrthoFinder
mkdir sequences
cd sequences

sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id= 'HWI-ST625-73-C0JUVACXX-7-AGALMA2';" > HWI-ST625-73-C0JUVACXX-7-AGALMA2.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='NCBI_HYDMAG';" >NCBI_HYDMAG.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-51-C02UNACXX-8-BARGMANNIA';" >HWI-ST625-51-C02UNACXX-8-BARGMANNIA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-51-C02UNACXX-6-FRILLAGALMA';" >HWI-ST625-51-C02UNACXX-6-FRILLAGALMA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='JGI_NEMVEC';" >JGI_NEMVEC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-51-C02UNACXX-7-NANOMIA';" >HWI-ST625-51-C02UNACXX-7-NANOMIA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-73-C0JUVACXX-7-TTAGGC';" >HWI-ST625-73-C0JUVACXX-7-TTAGGC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-6-ATCACG';" >HWI-ST625-54-C026EACXX-6-ATCACG.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-3-TATC';" >HWI-ST625-54-C026EACXX-3-TATC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-6-TTAGGC';" >HWI-ST625-54-C026EACXX-6-TTAGGC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='dbEST_CLYHEM';" >dbEST_CLYHEM.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-6-ACAGTG';" >HWI-ST625-54-C026EACXX-6-ACAGTG.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-6-CAGATC';" >HWI-ST625-54-C026EACXX-6-CAGATC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-7-TAGCTT';" >HWI-ST625-54-C026EACXX-7-TAGCTT.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-7-GGCTAC';" >HWI-ST625-54-C026EACXX-7-GGCTAC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-8-ATCACG';" >HWI-ST625-54-C026EACXX-8-ATCACG.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-73-C0JUVACXX-7-ATCACG';" >HWI-ST625-73-C0JUVACXX-7-ATCACG.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-7-CGATGT';" >HWI-ST625-54-C026EACXX-7-CGATGT.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-8-TTAGGC';" >HWI-ST625-54-C026EACXX-8-TTAGGC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-7-TGACCA';" >HWI-ST625-54-C026EACXX-7-TGACCA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-8-ACAGTG';" >HWI-ST625-54-C026EACXX-8-ACAGTG.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-7-GATCAG';" >HWI-ST625-54-C026EACXX-7-GATCAG.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-7-CTTGTA';" >HWI-ST625-54-C026EACXX-7-CTTGTA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-8-GCCAAT';" >HWI-ST625-54-C026EACXX-8-GCCAAT.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-8-CAGATC';" >HWI-ST625-54-C026EACXX-8-CAGATC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-8-ACTTGA';" >HWI-ST625-54-C026EACXX-8-ACTTGA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-61-C02G3ACxx-6-GGCTAC';" >HWI-ST625-61-C02G3ACxx-6-GGCTAC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-159-C4MVCACXX-5-CCGTCC';" >HWI-ST625-159-C4MVCACXX-5-CCGTCC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-159-C4MVCACXX-5-AGTTCC';" >HWI-ST625-159-C4MVCACXX-5-AGTTCC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-159-C4MVCACXX-5-TGACCA';" >HWI-ST625-159-C4MVCACXX-5-TGACCA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-181-C76K5ACXX-2-ATCACG';" >HWI-ST625-181-C76K5ACXX-2-ATCACG.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-181-C76K5ACXX-2-ACTTGA';" >HWI-ST625-181-C76K5ACXX-2-ACTTGA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-6-GCCAAT';" >HWI-ST625-54-C026EACXX-6-GCCAAT.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-181-C76K5ACXX-2-TAGCTT';" >HWI-ST625-181-C76K5ACXX-2-TAGCTT.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-181-C76K5ACXX-2-GGCTAC';" >HWI-ST625-181-C76K5ACXX-2-GGCTAC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='SRX231866';" >SRX231866.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='K00162-189-HJTYGBBXX-7-NCAGTG';" >K00162-189-HJTYGBBXX-7-NCAGTG.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-54-C026EACXX-6-GCCAAT';" >HWI-ST625-54-C026EACXX-6-GCCAAT.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HISEQ-129-C25BFACXX-8-HYDRACTINIA';" >HISEQ-129-C25BFACXX-8-HYDRACTINIA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST420-69-D0F2NACXX-3-ECTOPLEURA';" >HWI-ST420-69-D0F2NACXX-3-ECTOPLEURA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HISEQ-134-C27MTACXX-2-PODOCORYNA';" >HISEQ-134-C27MTACXX-2-PODOCORYNA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-159-C4MVCACXX-5-GTCCGC';" >HWI-ST625-159-C4MVCACXX-5-GTCCGC.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HISEQ-168-C3DEYACXX-8-ALATINA';" >HISEQ-168-C3DEYACXX-8-ALATINA.fa
sqlite3 $AGALMA_DB  "SELECT '>' || catalog.species ||'@'|| models.id || x'0A'|| sequences.sequence FROM agalma_homology AS homology JOIN agalma_homology_models AS homology_models JOIN agalma_models AS models JOIN agalma_sequences AS sequences JOIN catalog ON homology.id=homology_models.homology_id AND homology_models.model_id=models.id AND models.id=sequences.model_id AND catalog.id=models.catalog_id WHERE homology.run_id='81' AND sequences.type='a' AND models.catalog_id='HWI-ST625-181-C76K5ACXX-2-CTTGTA';" >HWI-ST625-181-C76K5ACXX-2-CTTGTA.fa
